import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="flex flex-col justify-center items-center">
      <Head>
        <title>DevMike9113's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[100vh] w-[100vw]">
        <h1 className="">DevMike9113's Portfolio</h1>
        <div className="flex rounded-xl border border-gray-100 mx-auto px-4 sm:px-6 h-2/3 w-2/3 lg:px-8 mt-32 h- bg-slate-200 text-gray-600">
          <div className="mx-auto max-w-3xl">
            <div className="shadow-sm shadow-gray-400 rounded-lg p-10">
              <a href="https://www.GitHub.com/devmike9113" className="">
                GitHub
              </a>
            </div>
            <div className="shadow-sm shadow-gray-400 rounded-lg p-10">
              <a
                href="https://www.linkedin.com/in/micheal-skinner-6b5675b0/"
                className=""
              >
                Linkedin
              </a>
            </div>
          </div>
          <div className="  shadow-sm shadow-gray-400 rounded-lg p-10">
            <Image
              src="/images/DevMike9113.jpeg"
              alt="DevMike9113"
              width={500}
              height={500}
            />
          </div>
        </div>
      </main>

      <footer className="absolute bottom-10">Good Bye World!</footer>
    </div>
  );
}
